# Generated by Django 4.1.2 on 2022-11-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remera',
            name='color',
            field=models.CharField(max_length=64, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='genero',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Unisex', 'Unisex')], max_length=6, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='lisa',
            field=models.BooleanField(blank=True, verbose_name='Lisa'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='marca',
            field=models.CharField(max_length=64, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='talle',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, verbose_name='Talle'),
        ),
    ]
